name: Bug report
title: "[BUG] "
description: Report the bug you encountered
labels: ["pending triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill this out. Before submitting, please make sure you have done the following
        1. Please **make sure** you have read the [GKD official docs](https://gkd.li) and the [FAQ](https://gkd.li/guide/faq)
        2. Please **check** whether this is an issue with a third-party rule subscription. If so, you should report it to the rule provider instead of here — **this tracker only accepts issues with the GKD app itself**
        3. Please **make sure** no one has already submitted a similar [issue](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) or [discussion](https://github.com/orgs/gkd-kit/discussions?discussions_q=); if one exists, please discuss there instead
        4. Please **make sure** your issue reproduces on the latest [release](https://github.com/gkd-kit/gkd/releases/latest) (including beta versions) — if not, please update to the latest version to reproduce before submitting
  - type: textarea
    id: log-file
    attributes:
      label: |
        Log file
      description: |
        Home - Settings - About - Logs, upload the log file or generate a link and paste it into the box below\
        A log file is required for any issue, otherwise it will be closed directly — please don't submit plain text/screenshots/videos only
    validations:
      required: true
  - type: textarea
    id: bug-1
    attributes:
      label: |
        Bug description (text/screenshots/video)
      description: |
        Please give as accurate a description as possible, otherwise your issue will be closed directly\
        Also, if your issue is about a snapshot/selector, you must provide the snapshot link or snapshot file, otherwise your issue will be closed directly
    validations:
      required: true
  - type: textarea
    id: bug-2
    attributes:
      label: |
        Expected behavior (text/screenshots/video)
      description: |
        Please give as accurate a description as possible, otherwise your issue will be closed directly
    validations:
      required: true
  - type: textarea
    id: bug-3
    attributes:
      label: |
        Actual behavior (text/screenshots/video)
      description: |
        Please give as accurate a description as possible, otherwise your issue will be closed directly
    validations:
      required: true
