blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/gkd-kit/gkd/discussions
    about: 'Other questions or requests: selectors/rules/snapshots/accessibility/devices, etc. If a search of issues turns up nothing, search discussions instead'
