name: Feature request
title: "[Feature] "
description: Propose your feature request
labels: ["pending triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill this out. Before submitting, please make sure you have done the following
        1. GKD does not provide any rules by default. You can check the [GKD official docs](https://gkd.li) and write your own rules, or import a remote subscription — please don't submit issues like "I want rule XXX"
        2. Please **check** whether this is a feature request for a third-party rule subscription. If so, you should report it to the rule provider instead of here — **this tracker only accepts feature requests for the GKD app itself**
        3. Please **make sure** no one has already submitted a similar [issue](https://github.com/gkd-kit/gkd/issues?q=is%3Aissue) or [discussion](https://github.com/orgs/gkd-kit/discussions?discussions_q=); if one exists, please discuss there instead
        4. Please **make sure** the feature you want is not already present in the latest [release](https://github.com/gkd-kit/gkd/releases/latest) (including beta versions) — if it might be, please update to the latest version to verify before submitting
  - type: textarea
    id: feature-description
    attributes:
      label: |
        Feature description
      description: |
        E.g.: I'd like a feature added to a specific page in GKD, and what that feature should do\
        Or a field added to the rule definition, and what that field should do\
        Please give an accurate description, otherwise your issue will be closed directly
    validations:
      required: true
